# Generated by Django 3.1.1 on 2020-10-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_cart_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupone',
            name='finish_at',
            field=models.DateField(default='2020-10-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupone',
            name='start_at',
            field=models.DateField(default='2020-10-20'),
            preserve_default=False,
        ),
    ]
