# Generated by Django 3.1.2 on 2020-10-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('1', 'fruct'), ('2', 'veg'), (None, 'Unknown')], max_length=20, null=True)),
                ('price', models.FloatField()),
                ('discount_price', models.IntegerField()),
                ('descount', models.IntegerField()),
            ],
        ),
    ]
