# Generated by Django 3.1.2 on 2020-10-28 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0003_auto_20201028_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descount',
            new_name='discount',
        ),
    ]
