# Generated by Django 3.1.2 on 2020-10-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0004_auto_20201028_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('min_coast', models.IntegerField()),
                ('start_at', models.DateField()),
                ('finish_at', models.DateField()),
            ],
        ),
    ]
