# Generated by Django 3.1.2 on 2020-10-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0005_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
